excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://venkateshshukla.github.io
title: Venkatesh Shukla
tagline: Code ramblings
description: Code ramblings
paginate: 5
google_analytics: UA-88866714-2
